import 'package:flutter/material.dart';
import 'package:kosan_santuy/bloc/blocs.dart';
import 'package:kosan_santuy/models/models.dart';
import 'package:kosan_santuy/services/services.dart';
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'package:kosan_santuy/shared/shared.dart';
import 'package:provider/provider.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:bloc/bloc.dart';
import 'package:kosan_santuy/shared/shared.dart';
import 'package:email_validator/email_validator.dart';
import 'package:another_flushbar/flushbar.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';

part 'splash_page.dart';
part 'sign_in_page.dart';
part 'main_page.dart';
part 'wrapper.dart';
part 'sign_up_page.dart';
part 'preference_page.dart';
part 'account_confirmation_page.dart';
