import 'package:flutter/material.dart';
import 'package:kosan_santuy/bloc/blocs.dart';
import 'package:kosan_santuy/services/services.dart';
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'package:kosan_santuy/shared/shared.dart';
import 'package:provider/provider.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:bloc/bloc.dart';
import 'package:kosan_santuy/shared/shared.dart';
part 'splash_page.dart';
part 'sign_in_page.dart';
part 'main_page.dart';
part 'wrapper.dart';
